quarkus.s3.devservices.enabled=false

quarkus.s3.aws.aws.credentials.type=static
quarkus.s3.aws.region=us-east-1
quarkus.s3.aws.credentials.static-provider.access-key-id=${AWS_ACCESS_KEY_ID}
quarkus.s3.aws.credentials.static-provider.secret-access-key=${AWS_SECRET_ACCESS_KEY}

expense.s3.bucket-name=guru-quarkus-expense-flow

quarkus.hibernate-orm.schema-management.strategy=update
quarkus.hibernate-orm.mapping.format.global=ignore

quarkus.langchain4j.openai.api-key=${OPENAI_API_KEY}

quarkus.langchain4j.log-requests=true

quarkus.log.category."dev.langchain4j.agentic.observability.ListenerNotifierUtil".level=OFF